# Generated by Django 5.0.1 on 2024-01-28 02:22

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_remove_beneficiario_endereco_beneficiario_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
