# Generated by Django 5.0.1 on 2024-01-29 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_alter_beneficiario_bairro_alter_beneficiario_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cep',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='O CEP deve ter 8 dígitos numéricos', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve ter 11 dígitos numéricos', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='logradouro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
