# Generated by Django 5.0.1 on 2024-01-26 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefeitura', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone_responsavel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
