# Generated by Django 5.0.1 on 2024-01-27 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefeituras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve ter 11 dígitos numéricos', regex='^\\d{11}$')])),
                ('cnh', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='A CNH deve ter 11 dígitos numéricos', regex='^\\d{11}$')])),
                ('telefone_contato', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('capacidade_pipa_litros', models.PositiveIntegerField()),
                ('placa_carro_pipa', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='A placa do carro deve estar no formato AAA9999', regex='^[A-Z]{3}\\d{4}$')])),
                ('fonte_agua', models.CharField(max_length=255)),
                ('prefeitura_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefeituras.prefeitura')),
            ],
        ),
    ]
