# Generated by Django 5.0.1 on 2024-01-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0002_remove_beneficiario_endereco_beneficiario_bairro_and_more'),
        ('pipeiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_agendamento', models.DateTimeField()),
                ('status_entrega', models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('E', 'Em andamento'), ('X', 'Cancelada')], default='P', max_length=1)),
                ('quantidade_agua_entregue_litros', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
                ('pipeiro_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeiros.pipeiro')),
            ],
        ),
    ]
